### ISSUE TITLE
Is it possible to use this project in an app for iOS?

### ISSUE THREAD

**Issue by jargomarg** [ChrisAU/Dawg#3]
I am really interested in this project but still gaining experience, so i'm sorry if these are stupid questions. Are those methods you listed only accessible via the command line, or is the command line just used for setting up the dictionary?

**Comment by cjnevin** [comment]
The command line is only used for creating the output dictionary (which could also be done by an app but would be slow), you could copy the output dictionary (created by DawgBuilder.swift) into an iOS/Mac app and use the Dawg.swift class exclusively.
